create table tb_sales (id int8 generated by default as identity, amount float8, date date, deals int4, visited int4, seller_id int8, primary key (id));
create table tb_sellers (id int8 generated by default as identity, name varchar(255), primary key (id));
alter table if exists tb_sales add constraint FKp0nn0oixeiw2fq3jivj6vnsu foreign key (seller_id) references tb_sellers;




postgres://

username: rbmpzcptmodmuu

senha:  c99816e85c7926075e8afb282a6c844d0da6c19744f2d7373cafb84ab5670427
@

host: ec2-34-206-8-52.compute-1.amazonaws.com

porta:  5432/

name banco: da533bm9lp3jc5



==============




postgres://

username:  pszdssmnvmpnon
pasword:b0284c5cc2fa54fcb11eaec79d8f48c38093369abf8fd136e40f0b41055ababf
host: ec2-54-163-254-204.compute-1.amazonaws.com
port:5432
db:dbr32r8p85elua